# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ForensiDoc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ForensiDoc

 pod 'what3words'

  target 'ForensiDocTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
